# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hive
tagline: A software developer
email: &email soongwonjun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Post anything
baseurl: / # the subpath of your site, e.g. /blog
url: https://soongwonjun.github.io # the base hostname & protocol for your site, e.g. http://example.com
repository: &repository https://github.com/soongwonjun
domain: soongwonjun.github.io
# twitter_username: soongwon Jun
# github_username:  soongwonjun
author:
  name: &name Soongwon Jun
  intro: A backend software engineer
  links:
  - title: Email
    url: *email
    icon: fas fa-envelope
  - title: Github
    url: *repository
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/soongwon-jun
    icon: fab fa-linkedin


# Build settings
plugins:
- jekyll-feed
# - jekyll-paginate
- jekyll-seo-tag
# - jekyll-toc

paginate: 10

sidebar:
  navigation:
  - title: Home
    url: /
  # - title: Archives
  #   url: /pages/archives/
  # - title: Categories
  #   url: /pages/categories/
  - title: Tags
    url: /pages/tags/

comment:
  utterance: true
  disqus: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
